Addressing second round of Ravi's comments

diff --git a/src/cmds/scripts/pbs_snapshot b/src/cmds/scripts/pbs_snapshot
--- a/src/cmds/scripts/pbs_snapshot
+++ b/src/cmds/scripts/pbs_snapshot
@@ -38,30 +38,61 @@
 ptllibpath=
 ptlbinpath=
 
+# Try rpm install paths
+if [ -f "/etc/debian_version" ]; then
+    ptl_prefix_lib=$(dpkg -L pbspro-ptl 2>/dev/null | grep -m 1 lib$ 2>/dev/null)
+else
+    ptl_prefix_lib=$(rpm -ql pbspro-ptl 2>/dev/null | grep -m 1 lib$ 2>/dev/null)
+fi
+
+# Try system paths
+if [ ! -d  ${ptl_prefix_lib} ]; then
+    ptl_prefix_lib=/usr/local/lib/python3.[[:digit:]]/site-packages
+    if [ ! -d  ${ptl_prefix_lib} ]; then
+        ptl_prefix_lib=/usr/lib/python3.[[:digit:]]/site-packages
+    fi
+fi
+
 conf="${PBS_CONF_FILE:-/etc/pbs.conf}"
 if [ -r "${conf}" ]; then
     # we only need PBS_EXEC from pbs.conf
     __PBS_EXEC=$( grep '^[[:space:]]*PBS_EXEC=' "$conf" | tail -1 | sed 's/^[[:space:]]*PBS_EXEC=\([^[:space:]]*\)[[:space:]]*/\1/' )
 else
-	echo "***" >&2
-	echo "Unable to read PBS config file" >&2
-	echo "***" >&2
+	echo "Error: Unable to read PBS conf file" >&2
 	exit 1
 fi
-
 unset conf
-if [ "X${__PBS_EXEC}" != "X" ]; then
-	ptlbinpath=${__PBS_EXEC}/unsupported/fw/bin
-	ptllibpath=${__PBS_EXEC}/unsupported/fw
+
+if [ "x${ptl_prefix_lib}" != "x" ]; then
+    python_dir=$(/bin/ls -1 ${ptl_prefix_lib})
+    prefix=$(dirname ${ptl_prefix_lib})
+
+    ptllibpath=${prefix}/lib/${python_dir}/site-packages
+    ptlbinpath=${prefix}/bin
+else
+    if [ "X${__PBS_EXEC}" != "X" ]; then
+        # Define PATH and PYTHONPATH for the users
+        PTL_PREFIX=$(dirname ${__PBS_EXEC})/ptl
+        if [ ! -x "${PTL_PREFIX}/lib/site-packages" ]; then
+            ptlbinpath=${__PBS_EXEC}/unsupported/fw/bin
+			ptllibpath=${__PBS_EXEC}/unsupported/fw
+        else
+            python_dir=$(/bin/ls -1 ${PTL_PREFIX}/lib)/site-packages
+            ptllibpath=${PTL_PREFIX}/lib/${python_dir}
+            ptlbinpath=${PTL_PREFIX}/bin
+        fi
+       unset PTL_PREFIX
+       unset python_dir
+    fi
 fi
 
 export PYTHONPATH=${ptllibpath}:${PYTHONPATH}
 
 if [ -x $ptlbinpath ] && [ -x $ptllibpath ];then
-	if [ -x "${__PBS_EXEC}/python/bin/python" ]; then
-		${__PBS_EXEC}/python/bin/python ${ptlbinpath}/pbs_snapshot.py "${@}"
-	else
-		python3 ${ptlbinpath}/pbs_snapshot.py "${@}"
+    if [ -x "${__PBS_EXEC}/python/bin/python" ]; then
+        ${__PBS_EXEC}/python/bin/python ${ptlbinpath}/pbs_snapshot.py "${@}"
+    else
+        python3 ${ptlbinpath}/pbs_snapshot.py "${@}"
     fi
 else
 	echo "***" >&2
