Rename PBSPro to OpenPBS (#1667)

diff --git a/src/cmds/scripts/pbs_dataservice b/src/cmds/scripts/pbs_dataservice
--- a/src/cmds/scripts/pbs_dataservice
+++ b/src/cmds/scripts/pbs_dataservice
@@ -3,37 +3,40 @@
 # Copyright (C) 1994-2020 Altair Engineering, Inc.
 # For more information, contact Altair at www.altair.com.
 #
-# This file is part of the PBS Professional ("PBS Pro") software.
+# This file is part of both the OpenPBS software ("OpenPBS")
+# and the PBS Professional ("PBS Pro") software.
 #
 # Open Source License Information:
 #
-# PBS Pro is free software. You can redistribute it and/or modify it under the
-# terms of the GNU Affero General Public License as published by the Free
-# Software Foundation, either version 3 of the License, or (at your option) any
-# later version.
+# OpenPBS is free software. You can redistribute it and/or modify it under
+# the terms of the GNU Affero General Public License as published by the
+# Free Software Foundation, either version 3 of the License, or (at your
+# option) any later version.
 #
-# PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
-# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
-# FOR A PARTICULAR PURPOSE.
-# See the GNU Affero General Public License for more details.
+# OpenPBS is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
+# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
+# License for more details.
 #
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 # Commercial License Information:
 #
-# For a copy of the commercial license terms and conditions,
-# go to: (http://www.pbspro.com/UserArea/agreement.html)
-# or contact the Altair Legal Department.
+# PBS Pro is commercially licensed software that shares a common core with
+# the OpenPBS software.  For a copy of the commercial license terms and
+# conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
+# Altair Legal Department.
 #
-# Altair’s dual-license business model allows companies, individuals, and
-# organizations to create proprietary derivative works of PBS Pro and
+# Altair's dual-license business model allows companies, individuals, and
+# organizations to create proprietary derivative works of OpenPBS and
 # distribute them - whether embedded or bundled with other software -
 # under a commercial license agreement.
 #
-# Use of Altair’s trademarks, including but not limited to "PBS™",
-# "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
-# trademark licensing policies.
+# Use of Altair's trademarks, including but not limited to "PBS™",
+# "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
+# subject to Altair's trademark licensing policies.
+
 
 . ${PBS_CONF_FILE:-/etc/pbs.conf}
 
@@ -57,7 +60,7 @@ get_db_user() {
 
 # The get_port function does the following:
 # Setting PBS_DATA_SERVICE_PORT based on availability  in following order:
-# 1. Set PBS_DATA_SERVICE_PORT to port provided by pbs 
+# 1. Set PBS_DATA_SERVICE_PORT to port provided by pbs
 # 2. Set PBS_DATA_SERVICE_PORT to port provided by pbs.conf
 # 3. Set PBS_DATA_SERVICE_PORT to port provided by /etc/services
 # 4. Set PBS_DATA_SERVICE_PORT to default port
@@ -66,7 +69,7 @@ get_port() {
 
 	if [ "$1" ]; then
 		PBS_DATA_SERVICE_PORT="$1"
-		
+
 	else
 		if [ -z "${PBS_DATA_SERVICE_PORT}" ]; then
 		    PBS_DATA_SERVICE_PORT=`awk '{if($1=="pbs_dataservice") {x=$2}} END {{split(x,a,"/")} {if ( a[2] == "tcp" ) print a[1]}}' /etc/services`
@@ -163,10 +166,10 @@ fi
 
 #
 # The check_status function does the following:
-# Checks what pg_ctl thinks about the database status. If pg_ctl says db is up, 
+# Checks what pg_ctl thinks about the database status. If pg_ctl says db is up,
 # just return 0 (running locally) else check if the datastore directory can be
 # locked.
-# If we cannot obtain exclusive lock, then return 2 
+# If we cannot obtain exclusive lock, then return 2
 #
 # Return code values:
 #	-1 - failed to execute
@@ -191,9 +194,9 @@ check_status() {
 
   if [ ${status} -eq 0 ]; then
 	echo "$res" | grep 'no server running'
-	if [ $? -eq 0 ]; then 
-		status=1 
-	else 
+	if [ $? -eq 0 ]; then
+		status=1
+	else
 		msg="PBS data service running locally"
 	fi
   else
@@ -226,11 +229,11 @@ oom_protect() {
 
 
 #
-# Launch monitoring by invoking the pbs_dataservice_monitor program 
-# with the "monitor" parameter. If the monitor returns a 0 exit status, it 
+# Launch monitoring by invoking the pbs_dataservice_monitor program
+# with the "monitor" parameter. If the monitor returns a 0 exit status, it
 # means it has been able to aquire a lock on a flag file, and so we can continue
 # to start the data service by calling pg_ctl.
-# This function also protects the database and the monitoring script from the 
+# This function also protects the database and the monitoring script from the
 # OOM on linux.
 # This function checks whether systemd (i.e. systemctl) is available on system or not?
 # If systemctl is available then register database processes with pbs.service
@@ -314,13 +317,13 @@ start_dataservice() {
 
 data_srv_mon="${PBS_EXEC}/sbin/pbs_ds_monitor"
 
-# 
+#
 # If second parameter is specified as "PBS" it means this was called from the PBS daemons
 # In such a case we do not want to be very verbose (as we only need the error code and msg)
 # When stop is called from command line we do a regular postgres stop, but when called from PBS
 # we do a "fast" stop of postgres. The "fast" stop disconnects any existing clients to ensure that
 # the postgres daemons are indeed stopped when PBS is stopped
-# 
+#
 
 case "$1" in
 	start|startasync)
@@ -339,8 +342,7 @@ case "$1" in
 					cat $log_file 2> /dev/null
 					if [ ${ret} -eq ${version_mismatch} ]; then
 						echo "PBS database needs to be upgraded."
-						echo "Please follow the upgrade instructions in the release notes for the v18.1.2 release at:"
-						echo "https://github.com/PBSPro/pbspro/releases"
+						echo "Consult the documentation/release notes for details."
 					fi
 				fi
 			fi
@@ -423,7 +425,7 @@ case "$1" in
 		fi
 		exit ${ret}
 		;;
-	
+
 	status)
 		check_status
 		ret=$?
diff --git a/src/cmds/scripts/pbs_habitat.in b/src/cmds/scripts/pbs_habitat.in
--- a/src/cmds/scripts/pbs_habitat.in
+++ b/src/cmds/scripts/pbs_habitat.in
@@ -3,37 +3,40 @@
 # Copyright (C) 1994-2020 Altair Engineering, Inc.
 # For more information, contact Altair at www.altair.com.
 #
-# This file is part of the PBS Professional ("PBS Pro") software.
+# This file is part of both the OpenPBS software ("OpenPBS")
+# and the PBS Professional ("PBS Pro") software.
 #
 # Open Source License Information:
 #
-# PBS Pro is free software. You can redistribute it and/or modify it under the
-# terms of the GNU Affero General Public License as published by the Free
-# Software Foundation, either version 3 of the License, or (at your option) any
-# later version.
+# OpenPBS is free software. You can redistribute it and/or modify it under
+# the terms of the GNU Affero General Public License as published by the
+# Free Software Foundation, either version 3 of the License, or (at your
+# option) any later version.
 #
-# PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
-# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
-# FOR A PARTICULAR PURPOSE.
-# See the GNU Affero General Public License for more details.
+# OpenPBS is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
+# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
+# License for more details.
 #
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 # Commercial License Information:
 #
-# For a copy of the commercial license terms and conditions,
-# go to: (http://www.pbspro.com/UserArea/agreement.html)
-# or contact the Altair Legal Department.
+# PBS Pro is commercially licensed software that shares a common core with
+# the OpenPBS software.  For a copy of the commercial license terms and
+# conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
+# Altair Legal Department.
 #
-# Altair’s dual-license business model allows companies, individuals, and
-# organizations to create proprietary derivative works of PBS Pro and
+# Altair's dual-license business model allows companies, individuals, and
+# organizations to create proprietary derivative works of OpenPBS and
 # distribute them - whether embedded or bundled with other software -
 # under a commercial license agreement.
 #
-# Use of Altair’s trademarks, including but not limited to "PBS™",
-# "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
-# trademark licensing policies.
+# Use of Altair's trademarks, including but not limited to "PBS™",
+# "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
+# subject to Altair's trademark licensing policies.
+
 
 if [ $# -eq 1 -a "$1" = "--version" ]; then
    echo pbs_version = @PBS_VERSION@
@@ -241,7 +244,7 @@ upgrade_pbs_database() {
 		echo "Database version file: ${data_dir}/PG_VERSION not found, cannot continue"
 		return 1
 	fi
-	
+
 	sys_pgsql_ver=$(echo `${PGSQL_BIN}/postgres -V` | awk 'NR==1 {print $NF}' | cut -d '.' -f 1,2)
 	old_pgsql_ver=`cat ${data_dir}/PG_VERSION`
 	# strip the minor version from sys_pgsql_ver if old_pgsql_ver does not have minor version (for comparison).
@@ -532,11 +535,11 @@ if [ -f "$PBS_HOME/pbs_version" ]; then
 	old_pbs_version=`cat $PBS_HOME/pbs_version`
 fi
 
-# Get the current PBS Pro version from qstat
+# Get the current PBS version from qstat
 if [ -x "$PBS_EXEC/bin/qstat" ]; then
 	pbs_version=`"${PBS_EXEC}/bin/qstat" --version | sed -e 's/^.* = //'`
 	if [ -z "$pbs_version" ]; then
-		echo "*** Could not obtain PBS Pro version from qstat"
+		echo "*** Could not obtain PBS version from qstat"
 		exit 1
 	fi
 	if [ "$pbs_version" != "$PBS_VERSION" ]; then
@@ -552,18 +555,18 @@ fi
 
 # Perform sanity check on server name in pbs.conf
 server_hostname=`get_server_hostname`
-[ "$server_hostname" = 'change_this_to_pbs_pro_server_hostname' ] && server_hostname=''
+[ "$server_hostname" = 'change_this_to_pbs_server_hostname' ] && server_hostname=''
 if [ -z "${server_hostname}" ] ; then
 	echo "***" >&2
-	echo "*** The hostname of the PBS Pro server in ${conf} is invalid." >&2
-	echo "*** Update the configuration file before starting PBS Pro." >&2
+	echo "*** The hostname of the PBS server in ${conf} is invalid." >&2
+	echo "*** Update the configuration file before starting PBS." >&2
 	echo "***" >&2
 	exit 1
 fi
 check_hostname "${server_hostname}"
 if [ $? -ne 0 ]; then
 	echo "***" >&2
-	echo "*** The PBS Pro server could not be found: $server_hostname" >&2
+	echo "*** The PBS server could not be found: $server_hostname" >&2
 	echo "*** This value must resolve to a valid IP address." >&2
 	echo "***" >&2
 	exit 1
@@ -576,7 +579,7 @@ if [ -f "$PBS_HOME/mom_priv/config" ]; then
 	cmd="$cmd | sed -e 's/\t/ /g' -e 's/ \\+/ /g' -e 's/^ //' -e 's/ $//'"
 	cmd="$cmd | grep '\\\$clienthost' | cut -d' ' -f2"
 	for host in `eval $cmd`; do
-		if [ -z "$host" -o "$host" = 'CHANGE_THIS_TO_PBS_PRO_SERVER_HOSTNAME' ]; then
+		if [ -z "$host" -o "$host" = 'CHANGE_THIS_TO_PBS_SERVER_HOSTNAME' ]; then
 			echo "***" >&2
 			echo "*** Invalid entry in $PBS_HOME/mom_priv/config" >&2
 			echo "*** for clienthost: $host" >&2
@@ -662,11 +665,10 @@ if [ "${PBS_START_SERVER:-0}" != 0 ] ; then
 		ret=$?
 		if [ $ret -ne 0 ]; then
 			if [ $ret -eq 2 ]; then
-				echo "It appears that PostgreSQL has been upgraded independently of PBS Pro."
-				echo "The PBS Pro database must be manually upgraded. Please refer to the"
-				echo "instructions in the release notes for version @PBS_VERSION@ located here:"
-				echo "https://github.com/PBSPro/pbspro/releases"
-			else 
+				echo "It appears that PostgreSQL has been upgraded independently of PBS."
+				echo "The PBS database must be manually upgraded. Please refer to the"
+				echo "documentation/release notes for details."
+			else
 				echo "Failed to upgrade PBS Datastore"
 			fi
 			exit $ret
@@ -679,7 +681,7 @@ if [ "${PBS_START_SERVER:-0}" != 0 ] ; then
 					echo "*** For future upgrades to be successful run the below command."
 					echo "*** cp -pr ${PBS_EXEC}/pgsql ${PBS_HOME}/pgsql.forupgrade"
 				else
-					echo "*** ${PBS_HOME}/$(basename ${old_inst_dir}).pre.${PBS_VERSION} may need to be manually removed if you do not wish to downgrade PBSPro."
+					echo "*** ${PBS_HOME}/$(basename ${old_inst_dir}).pre.${PBS_VERSION} may need to be manually removed if you do not wish to downgrade PBS."
 				fi
 			fi
 		fi
