Execution only rpm install fails (#1935)

diff --git a/src/cmds/scripts/pbs_habitat.in b/src/cmds/scripts/pbs_habitat.in
--- a/src/cmds/scripts/pbs_habitat.in
+++ b/src/cmds/scripts/pbs_habitat.in
@@ -244,13 +244,13 @@ if [ -f "$PBS_HOME/mom_priv/config" ]; then
 	done
 fi
 
-# Check for the db install script
-if [ ! -x "${PBS_EXEC}/libexec/pbs_db_utility" ]; then
-	echo "${PBS_EXEC}/libexec/pbs_db_utility not found"
-	exit 1
-fi
-
 if [ "${PBS_START_SERVER:-0}" != 0 ] ; then
+	# Check for the db install script
+	if [ ! -x "${PBS_EXEC}/libexec/pbs_db_utility" ]; then
+		echo "${PBS_EXEC}/libexec/pbs_db_utility not found"
+		exit 1
+	fi
+
 	# Source the file that sets DB env variables
 	. "$PBS_EXEC"/libexec/pbs_db_env
 	if [ $? -ne 0 ]; then
