PP-746: Extend PBS to support a list of scheduler objects

diff --git a/src/cmds/scripts/pbs_habitat.in b/src/cmds/scripts/pbs_habitat.in
--- a/src/cmds/scripts/pbs_habitat.in
+++ b/src/cmds/scripts/pbs_habitat.in
@@ -521,6 +521,22 @@ upgrade_pbs_schema() {
 		return 1
 	fi
 
+
+	if [ "$ver" = "1.2.0" ]; then
+		upgrade_pbs_schema_from_v1_2_0
+		ret=$?
+		if [ $ret -ne 0 ]; then
+			return $ret
+		fi
+	else
+		echo "Cannot upgrade PBS datastore version $ver"
+		ret=$?
+		if [ $ret -ne 0 ]; then
+			return $ret
+		fi
+		return 1
+	fi
+	
 	${PBS_EXEC}/sbin/pbs_dataservice status > /dev/null
 	if [ $? -eq 1 ]; then
 		# not running, start now
@@ -626,6 +642,29 @@ upgrade_pbs_schema_from_v1_1_0() {
 		alter table pbs.subjob_track drop constraint subjob_track_pkey cascade;
 		create index subjob_jid_idx on pbs.subjob_track (ji_jobid, trk_index);
 		update pbs.info set pbs_schema_version = '1.2.0';
+	EOF
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		echo "Some datastore transformations failed to complete"
+		echo "Please check dataservice logs"
+		return $ret
+	fi
+}
+
+upgrade_pbs_schema_from_v1_2_0() {
+
+	${PGSQL_DIR}/bin/psql -p ${PBS_DATA_SERVICE_PORT} -d pbs_datastore -U ${PBS_DATA_SERVICE_USER} <<-EOF > /dev/null
+		INSERT INTO pbs.scheduler (sched_name, sched_sv_name, sched_savetm, sched_creattm) VALUES ('default', '1', localtimestamp, localtimestamp);
+		ALTER TABLE pbs.scheduler_attr DROP CONSTRAINT scheduler_attr_fk;
+		UPDATE pbs.scheduler_attr SET sched_name='default' WHERE sched_name='1'
+		ALTER TABLE pbs.scheduler_attr ADD CONSTRAINT scheduler_attr_fk
+			FOREIGN KEY (sched_name)
+			REFERENCES pbs.scheduler (sched_name)
+			ON DELETE CASCADE
+			ON UPDATE NO ACTION
+			NOT DEFERRABLE;
+		DELETE FROM pbs.scheduler WHERE sched_name='1';
+		update pbs.info set pbs_schema_version = '1.3.0';
 	EOF
 	ret=$?
 	if [ $ret -ne 0 ]; then
