PP-289: Unique Jobid's upto 1 trillion

diff --git a/src/cmds/scripts/pbs_habitat.in b/src/cmds/scripts/pbs_habitat.in
--- a/src/cmds/scripts/pbs_habitat.in
+++ b/src/cmds/scripts/pbs_habitat.in
@@ -42,7 +42,7 @@ fi
 
 PBS_VERSION=@PBS_VERSION@
 tmpdir=${PBS_TMPDIR:-${TMPDIR:-"/var/tmp"}}
-PBS_CURRENT_SCHEMA_VER='1.3.0'
+PBS_CURRENT_SCHEMA_VER='1.4.0'
 PBS_AES_SWITCH_VER='14.0'
 
 get_db_user() {
@@ -507,6 +507,15 @@ upgrade_pbs_schema() {
 			return $ret
 		fi
 		ver="1.3.0"
+	fi
+
+	if [ "$ver" = "1.3.0" ]; then
+		upgrade_pbs_schema_from_v1_3_0
+		ret=$?
+		if [ $ret -ne 0 ]; then
+			return $ret
+		fi
+		ver="1.4.0"
 	else
 		echo "Cannot upgrade PBS datastore version $ver"
 		ret=$?
@@ -641,6 +650,20 @@ upgrade_pbs_schema_from_v1_2_0() {
 			NOT DEFERRABLE;
 		DELETE FROM pbs.scheduler WHERE sched_name='1';
 		UPDATE pbs.info SET pbs_schema_version = '1.3.0';
+	EOF
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		echo "Some datastore transformations failed to complete"
+		echo "Please check dataservice logs"
+		return $ret
+	fi
+}
+
+upgrade_pbs_schema_from_v1_3_0() {
+
+	${PGSQL_DIR}/bin/psql -p ${PBS_DATA_SERVICE_PORT} -d pbs_datastore -U ${PBS_DATA_SERVICE_USER} <<-EOF > /dev/null
+		ALTER TABLE pbs.server ALTER COLUMN sv_jobidnumber TYPE BIGINT;
+		UPDATE pbs.info SET pbs_schema_version = '1.4.0';
 	EOF
 	ret=$?
 	if [ $ret -ne 0 ]; then
