Systemd service enhancement

diff --git a/src/cmds/scripts/pbs_init.d.in b/src/cmds/scripts/pbs_init.d.in
--- a/src/cmds/scripts/pbs_init.d.in
+++ b/src/cmds/scripts/pbs_init.d.in
@@ -258,7 +258,7 @@ check_hostname() {
 }
 
 start_pbs() {
-	echo "Starting PBS"
+	echo "Starting PBS $1"
 
 	# Perform sanity checks
 	server_hostname=`get_server_hostname`
@@ -294,7 +294,7 @@ start_pbs() {
 		homever=`cat ${PBS_HOME}/pbs_version`
 		[ "${qstatver}" != "${homever}" ] && needmakehome=3
 	fi
-	[ ${needmakehome} -eq 0 -a "${PBS_START_SERVER}" != "0" -a ! -d "${PBS_HOME}/datastore" ] && needmakehome=4
+	[ ${needmakehome} -eq 0 -a ! -d "${PBS_HOME}/datastore" ] && needmakehome=4
 
 	if [ ${needmakehome} -ne 0 -a ! -x ${PBS_EXEC}/libexec/pbs_habitat ]; then
 		echo "***" >&2
@@ -307,19 +307,19 @@ start_pbs() {
 		1)
 			echo PBS Home directory ${PBS_HOME} does not exist.
 			echo Running ${PBS_EXEC}/libexec/pbs_habitat to create it.
-			${PBS_EXEC}/libexec/pbs_habitat || return 1
+			${PBS_EXEC}/libexec/pbs_habitat $1 || return 1
 			echo Home directory ${PBS_HOME} created.
 			;;
 		2|3)
 			echo PBS Home directory ${PBS_HOME} needs updating.
 			echo Running ${PBS_EXEC}/libexec/pbs_habitat to update it.
-			${PBS_EXEC}/libexec/pbs_habitat || return 1
+			${PBS_EXEC}/libexec/pbs_habitat $1 || return 1
 			echo Home directory ${PBS_HOME} updated.
 			;;
 		4)
 			echo PBS Home directory ${PBS_HOME} needs datastore.
 			echo Running ${PBS_EXEC}/libexec/pbs_habitat to initialize it.
-			${PBS_EXEC}/libexec/pbs_habitat || return 1
+			${PBS_EXEC}/libexec/pbs_habitat $1 || return 1
 			echo Datastore directory ${PBS_HOME}/datastore initialized.
 			;;
 	esac
@@ -340,7 +340,7 @@ start_pbs() {
 		echo "Warning: Please inform your administrator immediately or contact Altair customer support"
 	fi
 
-	if [ "${PBS_START_COMM}" -gt 0 ]; then
+	if [ "$1" == "pbs_comm" -o "${PBS_START_COMM}" -gt 0 ]; then
 		if check_prog "pbs_comm" ; then
 			echo "PBS comm already running."
 		else
@@ -355,7 +355,7 @@ start_pbs() {
 		fi
 	fi
 
-	if [ "${PBS_START_MOM}" -gt 0 ]; then
+	if [ "$1" == "pbs_mom" -o "${PBS_START_MOM}" -gt 0 ]; then
 		if check_prog "mom" ; then
 			echo "PBS mom already running."
 		else
@@ -375,7 +375,7 @@ start_pbs() {
 		fi
 	fi
 
-	if [ "${PBS_START_SCHED}" -gt 0 ]; then
+	if [ "$1" == "pbs_sched" -o "${PBS_START_SCHED}" -gt 0 ]; then
 		if check_prog "sched" ; then
 			echo "PBS scheduler already running."
 		else
@@ -393,7 +393,7 @@ start_pbs() {
 		fi
 	fi
 
-	if [ "${PBS_START_SERVER}" -gt 0 ] ; then
+	if [ "$1" == "pbs_server" -o "${PBS_START_SERVER}" -gt 0 ] ; then
 		if check_prog "server" ; then
 			echo "PBS Server already running."
 		else
@@ -433,9 +433,9 @@ start_pbs() {
 }
 
 stop_pbs() {
-	echo "Stopping PBS"
+	echo "Stopping PBS $1"
 	update_pids
-	if [ "${PBS_START_SERVER}" -gt 0 ] ; then
+	if [ "$1" == "pbs_server" -o "${PBS_START_SERVER}" -gt 0 ] ; then
 		active_server=`lc_host_name \`${PBS_EXEC}/bin/qstat -Bf 2>/dev/null | \
 		grep "server_host = " | \
 		sed -e "s/.*server_host = //"\``
@@ -468,13 +468,13 @@ stop_pbs() {
 			${PBS_EXEC}/sbin/pbs_dataservice stop > /dev/null 2>&1
 		fi
 	fi
-	if [ "${PBS_START_MOM}" -gt 0 ] ; then
+	if [ "$1" == "pbs_mom" -o "${PBS_START_MOM}" -gt 0 ] ; then
 		if check_prog "mom" ; then
 			kill ${pbs_mom_pid}
 			echo "PBS mom - was pid: ${pbs_mom_pid}"
 		fi
 	fi
-	if [ "${PBS_START_SCHED}" -gt 0 ] ; then
+	if [ "$1" == "pbs_sched" -o "${PBS_START_SCHED}" -gt 0 ] ; then
 		if check_prog "sched" ; then
 			if [ ${is_secondary} -eq 0 ] ; then
 				kill ${pbs_sched_pid}
@@ -486,7 +486,7 @@ stop_pbs() {
 			fi
 		fi
 	fi
-	if [ "${PBS_START_COMM}" -gt 0 ] ; then
+	if [ "$1" == "pbs_comm" -o "${PBS_START_COMM}" -gt 0 ] ; then
 		if check_prog "pbs_comm" ; then
 			if [ ${is_secondary} -eq 0 ] ; then
 				kill -TERM ${pbs_comm_pid}
@@ -509,22 +509,22 @@ stop_pbs() {
 	do
 		sleep 1
 		something_running=""
-		if [ "${PBS_START_SERVER}" -gt 0 ] ; then
+		if [ "$1" == "pbs_server" -o "${PBS_START_SERVER}" -gt 0 ] ; then
 			if check_prog "server" ; then
 				something_running=" pbs_server"
 			fi
 		fi
-		if [ "${PBS_START_MOM}" -gt 0 ] ; then
+		if [ "$1" == "pbs_mom" -o "${PBS_START_MOM}" -gt 0 ] ; then
 			if check_prog "mom" ; then
 				something_running="${something_running} pbs_mom"
 			fi
 		fi
-		if [ "${PBS_START_SCHED}" -gt 0 ] ; then
+		if [ "$1" == "pbs_sched" -o "${PBS_START_SCHED}" -gt 0 ] ; then
 			if check_prog "sched" ; then
 				something_running="${something_running} pbs_sched"
 			fi
 		fi
-		if [ "${PBS_START_COMM}" -gt 0 ] ; then
+		if [ "$1" == "pbs_comm" -o "${PBS_START_COMM}" -gt 0 ] ; then
 			if check_prog "pbs_comm" ; then
 				something_running=" pbs_comm"
 			fi
@@ -534,34 +534,34 @@ stop_pbs() {
 		fi
 		waitloop=`expr ${waitloop} + 1`
 	done
-	echo "Unable to stop PBS,${something_running} still active"
+	echo "Unable to stop PBS $1 ,${something_running} still active"
 	exit 1
 }
 
 status_pbs() {
 	update_pids
-	if [ "${PBS_START_SERVER}" -gt 0 ]; then
+	if [ "$1" == "pbs_server" -o "${PBS_START_SERVER}" -gt 0 ]; then
 		if check_prog "server" ; then
 			echo "pbs_server is pid ${pid}"
 		else
 			echo "pbs_server is not running"
 		fi
 	fi
-	if [ "${PBS_START_MOM}" -gt 0 ]; then
+	if [ "$1" == "pbs_mom" -o "${PBS_START_MOM}" -gt 0 ]; then
 		if check_prog "mom" ; then
 			echo "pbs_mom is pid ${pbs_mom_pid}"
 		else
 			echo "pbs_mom is not running"
 		fi
 	fi
-	if [ "${PBS_START_SCHED}" -gt 0 ]; then
+	if [ "$1" == "pbs_sched" -o "${PBS_START_SCHED}" -gt 0 ]; then
 		if check_prog "sched" ; then
 			echo "pbs_sched is pid ${pbs_sched_pid}"
 		else
 			echo "pbs_sched is not running"
 		fi
 	fi
-	if [ "${PBS_START_COMM}" -gt 0 ]; then
+	if [ "$1" == "pbs_comm" -o "${PBS_START_COMM}" -gt 0 ]; then
 		if check_prog "pbs_comm" ; then
 			echo "pbs_comm is ${pbs_comm_pid}"
 		else
@@ -622,14 +622,14 @@ pre_start_pbs()
 		(
 			TEMP_DIR=${PBS_TMPDIR:-${TMPDIR:-"/var/tmp"}}
 			TEMPFILE=${TEMP_DIR}/start_pbs_logs_tmp_$$
-			start_pbs > ${TEMPFILE} 2>&1
+			start_pbs $1 > ${TEMPFILE} 2>&1
 			ret=$?
 			logger -i -t PBS -f ${TEMPFILE}
 			rm -f ${TEMPFILE}
 			exit ${ret}
 		) &
 	else
-		start_pbs
+		start_pbs $1
 		exit $?
 	fi
 }
@@ -718,18 +718,18 @@ case "`basename $0`" in
 				echo "Stopping PBS"
 				;;
 			status)
-				status_pbs
+				status_pbs "$2"
 				;;
 			start)
-				pre_start_pbs
+				pre_start_pbs "$2"
 				;;
 			stop)
-				stop_pbs
+				stop_pbs "$2"
 				;;
 			restart)
 				echo "Restarting PBS"
-				stop_pbs
-				pre_start_pbs
+				stop_pbs "$2"
+				pre_start_pbs "$2"
 				;;
 			*)
 				echo "Usage: `basename $0` --version"
diff --git a/src/cmds/scripts/pbs_postinstall.in b/src/cmds/scripts/pbs_postinstall.in
--- a/src/cmds/scripts/pbs_postinstall.in
+++ b/src/cmds/scripts/pbs_postinstall.in
@@ -188,10 +188,6 @@ create_conf() {
 			PBS_SERVER='CHANGE_THIS_TO_PBS_SERVER_HOSTNAME'
 			echo "PBS_SERVER=$PBS_SERVER" >>"$newconf"
 		fi
-		[ -z "$PBS_START_SERVER" ] && echo "PBS_START_SERVER=0" >>"$newconf"
-		[ -z "$PBS_START_SCHED" ] && echo "PBS_START_SCHED=0" >>"$newconf"
-		[ -z "$PBS_START_COMM" ] && echo "PBS_START_COMM=0" >>"$newconf"
-		[ -z "$PBS_START_MOM" ] && echo "PBS_START_MOM=0" >>"$newconf"
 	else
 		case $INSTALL_PACKAGE in
 		server)
@@ -199,33 +195,26 @@ create_conf() {
 				PBS_SERVER=`hostname | awk -F. '{print $1}'`
 				echo "PBS_SERVER=$PBS_SERVER" >>"$newconf"
 			fi
-			[ -z "$PBS_START_SERVER" ] && echo "PBS_START_SERVER=1" >>"$newconf"
-			[ -z "$PBS_START_SCHED" ] && echo "PBS_START_SCHED=1" >>"$newconf"
-			[ -z "$PBS_START_COMM" ] && echo "PBS_START_COMM=1" >>"$newconf"
-			[ -z "$PBS_START_MOM" ] && echo "PBS_START_MOM=0" >>"$newconf"
 			;;
 		execution)
 			if [ -z "$PBS_SERVER" ]; then
 				PBS_SERVER='CHANGE_THIS_TO_PBS_SERVER_HOSTNAME'
 				echo "PBS_SERVER=$PBS_SERVER" >>"$newconf"
 			fi
-			[ -z "$PBS_START_SERVER" ] && echo "PBS_START_SERVER=0" >>"$newconf"
-			[ -z "$PBS_START_SCHED" ] && echo "PBS_START_SCHED=0" >>"$newconf"
-			[ -z "$PBS_START_COMM" ] && echo "PBS_START_COMM=0" >>"$newconf"
-			[ -z "$PBS_START_MOM" ] && echo "PBS_START_MOM=1" >>"$newconf"
 			;;
 		client)
 			if [ -z "$PBS_SERVER" ]; then
 				PBS_SERVER='CHANGE_THIS_TO_PBS_SERVER_HOSTNAME'
 				echo "PBS_SERVER=$PBS_SERVER" >>"$newconf"
 			fi
-			[ -z "$PBS_START_SERVER" ] && echo "PBS_START_SERVER=0" >>"$newconf"
-			[ -z "$PBS_START_SCHED" ] && echo "PBS_START_SCHED=0" >>"$newconf"
-			[ -z "$PBS_START_COMM" ] && echo "PBS_START_COMM=0" >>"$newconf"
-			[ -z "$PBS_START_MOM" ] && echo "PBS_START_MOM=0" >>"$newconf"
 			;;
 		esac
 	fi
+
+	[ -z "$PBS_START_SERVER" ] && echo "PBS_START_SERVER=0" >>"$newconf"
+	[ -z "$PBS_START_SCHED" ] && echo "PBS_START_SCHED=0" >>"$newconf"
+	[ -z "$PBS_START_COMM" ] && echo "PBS_START_COMM=0" >>"$newconf"
+	[ -z "$PBS_START_MOM" ] && echo "PBS_START_MOM=0" >>"$newconf"
 
 	[ -z "$PBS_EXEC" ] && echo "PBS_EXEC=$newpbs_exec" >>"$newconf"
 	[ -z "$PBS_HOME" -a -n "$newpbs_home" ] && echo "PBS_HOME=$newpbs_home" >>"$newconf"
@@ -243,22 +232,42 @@ create_conf() {
 
 perform_checks() {
 	fail=0
-	if [ ${PBS_START_SERVER} != 0 -a ! -x ${PBS_EXEC}/sbin/pbs_server ] ;then
-		echo "*** Server does not exist!"
-		fail=1
+	if command -v systemctl >/dev/null 2>&1; then
+		if [ ! -x ${PBS_EXEC}/sbin/pbs_server ] ;then
+			echo "*** Server does not exist!"
+			fail=1
+		fi
+		if [ ! -x ${PBS_EXEC}/sbin/pbs_sched ] ;then
+			echo "*** Scheduler does not exist!"
+			fail=1
+		fi
+		if [ ! -x ${PBS_EXEC}/sbin/pbs_comm ] ;then
+			echo "*** Communication agent does not exist!"
+			fail=1
+		fi
+		if [ ! -x ${PBS_EXEC}/sbin/pbs_mom ] ;then
+			echo "*** MOM does not exist!"
+			fail=1
+		fi
+	else
+		if [ ${PBS_START_SERVER} != 0 -a ! -x ${PBS_EXEC}/sbin/pbs_server ] ;then
+			echo "*** Server does not exist!"
+			fail=1
+		fi
+		if [ ${PBS_START_SCHED} != 0 -a ! -x ${PBS_EXEC}/sbin/pbs_sched ] ;then
+			echo "*** Scheduler does not exist!"
+			fail=1
+		fi
+		if [ ${PBS_START_COMM} != 0 -a ! -x ${PBS_EXEC}/sbin/pbs_comm ] ;then
+			echo "*** Communication agent does not exist!"
+			fail=1
+		fi
+		if [ ${PBS_START_MOM} != 0 -a ! -x ${PBS_EXEC}/sbin/pbs_mom ] ;then
+			echo "*** MOM does not exist!"
+			fail=1
+		fi
 	fi
-	if [ ${PBS_START_SCHED} != 0 -a ! -x ${PBS_EXEC}/sbin/pbs_sched ] ;then
-		echo "*** Scheduler does not exist!"
-		fail=1
-	fi
-	if [ ${PBS_START_COMM} != 0 -a ! -x ${PBS_EXEC}/sbin/pbs_comm ] ;then
-		echo "*** Communication agent does not exist!"
-		fail=1
-	fi
-	if [ ${PBS_START_MOM} != 0 -a ! -x ${PBS_EXEC}/sbin/pbs_mom ] ;then
-		echo "*** MOM does not exist!"
-		fail=1
-	fi
+
 	if [ $fail -ne 0 ] ;then
 		echo "***"
 		echo "*** A required PBS executable is missing. This could be"
@@ -346,7 +355,7 @@ install_pbsinitd() {
 			if [ -x /sbin/chkconfig ] ; then
 				/sbin/chkconfig --add pbs
 			elif [ -x /usr/sbin/update-rc.d ] ; then
-				/usr/sbin/update-rc.d pbs enable
+				/usr/sbin/update-rc.d pbs enable 
 			else
 				ln -sf $initscript /etc/rc.d/rc0.d/K10pbs
 				ln -sf $initscript /etc/rc.d/rc1.d/K10pbs
@@ -361,17 +370,65 @@ install_pbsinitd() {
 				[ -f /etc/profile.d/pbs.sh ] || cp ${PBS_EXEC}/etc/pbs.sh /etc/profile.d
 			fi
 
-			pbs_unitfile="@_unitdir@/pbs.service"
+			pbs_unitfile="@_unitdir@/pbs_server.service"
 			if [ -f "${pbs_unitfile}" ]; then
 				presetdir="@_unitdir@-preset"
 				eval "sed -i 's;\(^[[:space:]]*SourcePath=\)[^[:space:]]*;\1${PBS_EXEC}/libexec/pbs_init.d;' \"$pbs_unitfile\""
 				eval "sed -i 's;\(^[[:space:]]*ExecStart=\)[^[:space:]]*;\1${PBS_EXEC}/libexec/pbs_init.d;' \"$pbs_unitfile\""
 				eval "sed -i 's;\(^[[:space:]]*ExecStop=\)[^[:space:]]*;\1${PBS_EXEC}/libexec/pbs_init.d;' \"$pbs_unitfile\""
 				if command -v systemctl >/dev/null 2>&1; then
-					systemctl enable pbs && systemctl daemon-reload
+					systemctl enable pbs_server && systemctl daemon-reload
 					if [ $? != 0 -a -d "${presetdir}" ]; then
 						echo "*** Creating preset file ${presetdir}/95-pbs.preset"
-						echo "enable pbs.service" > "${presetdir}/95-pbs.preset"
+						echo "enable pbs_server.service" > "${presetdir}/95-pbs.preset"
+					fi
+				else
+					echo "*** Systemctl binary is not available; Failed to register PBS as a service"
+				fi
+			fi
+			pbs_unitfile="@_unitdir@/pbs_mom.service"
+			if [ -f "${pbs_unitfile}" ]; then
+				presetdir="@_unitdir@-preset"
+				eval "sed -i 's;\(^[[:space:]]*SourcePath=\)[^[:space:]]*;\1${PBS_EXEC}/libexec/pbs_init.d;' \"$pbs_unitfile\""
+				eval "sed -i 's;\(^[[:space:]]*ExecStart=\)[^[:space:]]*;\1${PBS_EXEC}/libexec/pbs_init.d;' \"$pbs_unitfile\""
+				eval "sed -i 's;\(^[[:space:]]*ExecStop=\)[^[:space:]]*;\1${PBS_EXEC}/libexec/pbs_init.d;' \"$pbs_unitfile\""
+				if command -v systemctl >/dev/null 2>&1; then
+					systemctl enable pbs_mom && systemctl daemon-reload
+					if [ $? != 0 -a -d "${presetdir}" ]; then
+						echo "*** Creating preset file ${presetdir}/95-pbs.preset"
+						echo "enable pbs_mom.service" > "${presetdir}/95-pbs.preset"
+					fi
+				else
+					echo "*** Systemctl binary is not available; Failed to register PBS as a service"
+				fi
+			fi
+			pbs_unitfile="@_unitdir@/pbs_sched.service"
+			if [ -f "${pbs_unitfile}" ]; then
+				presetdir="@_unitdir@-preset"
+				eval "sed -i 's;\(^[[:space:]]*SourcePath=\)[^[:space:]]*;\1${PBS_EXEC}/libexec/pbs_init.d;' \"$pbs_unitfile\""
+				eval "sed -i 's;\(^[[:space:]]*ExecStart=\)[^[:space:]]*;\1${PBS_EXEC}/libexec/pbs_init.d;' \"$pbs_unitfile\""
+				eval "sed -i 's;\(^[[:space:]]*ExecStop=\)[^[:space:]]*;\1${PBS_EXEC}/libexec/pbs_init.d;' \"$pbs_unitfile\""
+				if command -v systemctl >/dev/null 2>&1; then
+					systemctl enable pbs_sched && systemctl daemon-reload
+					if [ $? != 0 -a -d "${presetdir}" ]; then
+						echo "*** Creating preset file ${presetdir}/95-pbs.preset"
+						echo "enable pbs_sched.service" > "${presetdir}/95-pbs.preset"
+					fi
+				else
+					echo "*** Systemctl binary is not available; Failed to register PBS as a service"
+				fi
+			fi
+			pbs_unitfile="@_unitdir@/pbs_comm.service"
+			if [ -f "${pbs_unitfile}" ]; then
+				presetdir="@_unitdir@-preset"
+				eval "sed -i 's;\(^[[:space:]]*SourcePath=\)[^[:space:]]*;\1${PBS_EXEC}/libexec/pbs_init.d;' \"$pbs_unitfile\""
+				eval "sed -i 's;\(^[[:space:]]*ExecStart=\)[^[:space:]]*;\1${PBS_EXEC}/libexec/pbs_init.d;' \"$pbs_unitfile\""
+				eval "sed -i 's;\(^[[:space:]]*ExecStop=\)[^[:space:]]*;\1${PBS_EXEC}/libexec/pbs_init.d;' \"$pbs_unitfile\""
+				if command -v systemctl >/dev/null 2>&1; then
+					systemctl enable pbs_comm && systemctl daemon-reload
+					if [ $? != 0 -a -d "${presetdir}" ]; then
+						echo "*** Creating preset file ${presetdir}/95-pbs.preset"
+						echo "enable pbs_comm.service" > "${presetdir}/95-pbs.preset"
 					fi
 				else
 					echo "*** Systemctl binary is not available; Failed to register PBS as a service"
